### ISSUE TITLE
com.intellij.openapi.vcs.VcsException: Failed to start Git process: Cannot run program "C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.3\bin\runnerw.exe" (in directory "C:\GIT\aaaaa.master"): CreateProcess error=206, The filename or extension is too long

### ISSUE THREAD

**Issue by igreenfield** [GitLiveApp/GitLive#115]
at git4idea.commands.GitCommandResult.throwOnError(GitCommandResult.java:156)
	at git4idea.commands.GitCommandResult.getOutputOrThrow(GitCommandResult.java:145)
	at dev.gitlive.af.invokeSuspend(SourceFile:166)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by nbransby** [comment]
Hi @igreenfield do you see "GitLive has stopped due to an uncaught exception" in the GitLive toolwindow when this issue occurs?

**Comment by Ygnys** [comment]
Hi @igreenfield, wanted to follow up on this issue, does it still happen in the newest version? If so, could you specify when it occurs and what's the name of the file you have opened ("The filename or extension is too long"). Thanks!

**Comment by Ygnys** [comment]
Closing the issue because it needs more information and has not had recent activity. Please re-open the issue if more details can be provided. Thanks!
