### ISSUE TITLE
issue with intellij idea 2024.2 plugin release 18.0.0-eap1

### ISSUE THREAD

**Issue by avallfox** [GitLiveApp/GitLive#157]
![Screenshot 2024-08-14 at 11 07 40](https://github.com/user-attachments/assets/eedd0ded-3d3d-49f9-9ca8-9c8b0a7980c0)

a@fl7v0s:p@1o71mhm java.util.ServiceConfigurationError: io.ktor.client.HttpClientEngineContainer: io.ktor.client.engine.java.JavaHttpEngineContainer not a subtype

java.util.ServiceConfigurationError: io.ktor.client.HttpClientEngineContainer: io.ktor.client.engine.java.JavaHttpEngineContainer not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1295)
	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1328)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1319)
	at io.ktor.client.HttpClientJvmKt.<clinit>(HttpClientJvm.kt:39)
	at dev.gitlive.internal.service.Host$Companion.a(SourceFile:288)
	at dev.gitlive.internal.service.Host$Companion.a(SourceFile:279)
	at dev.gitlive.internal.model.an.invokeSuspend(SourceFile:94)
	at dev.gitlive.internal.model.an.invoke(SourceFile:1000)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:29)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

**Comment by nbransby** [comment]
Sorry, this issue appears to affect self hosted remotes. We should have a fix for this tomorrow

**Comment by nbransby** [comment]
The fix is now available @avallfox
