### ISSUE TITLE
GitLive - a@1sgmjqb:s@3pnac5 dev.gitlive.model.w: 128: No tags can describe 'e183f9aa6de1119d7f2ec8ff867fc2bcf24beacf'

### ISSUE THREAD

**Issue by alesak** [GitLiveApp/GitLive#169]
`2024-10-19 00:20:25,773 [  27610] SEVERE - GitLive - a@1sgmjqb:s@3pnac5 dev.gitlive.model.w: 128: No tags can describe 'e183f9aa6de1119d7f2ec8ff867fc2bcf24beacf'.
Try --always, or create some tags.
dev.gitlive.model.w: 128: No tags can describe 'e183f9aa6de1119d7f2ec8ff867fc2bcf24beacf'.
Try --always, or create some tags.
	at dev.gitlive.model.t$b.a(SourceFile:61)
	at dev.gitlive.internal.model.f.emit(SourceFile:221)
	at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(Distinct.kt:73)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:115)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:84)
	at dev.gitlive.internal.c.O.invokeSuspend(SourceFile:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
2024-10-19 00:20:25,780 [  27617] SEVERE - GitLive - IntelliJ IDEA 2024.2.3  Build #IU-242.23339.11
2024-10-19 00:20:25,781 [  27618] SEVERE - GitLive - JDK: 21.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-10-19 00:20:25,781 [  27618] SEVERE - GitLive - OS: Linux
2024-10-19 00:20:25,782 [  27619] SEVERE - GitLive - Plugin to blame: GitLive version: 18.0.3`

**Comment by nbransby** [comment]
Thanks, we'll have a fix in the next release

**Comment by nbransby** [comment]
Hi, I believe this should be fixed in the latest version 18.0.4
